Print third-party heap version in -Xinternalversion and error report.
mmtk/openjdk pull request #14
Opened 2022-08-10 02:56 UTC by qinsoon

2022-08-11 12:45 UTC, wks requested changes
Only a small indentation problem.

2022-08-11 12:45 UTC, wks commented on src/hotspot/share/runtime/arguments.cpp
> +                ThirdPartyHeap::version());
In OpenJDK, arguments are indented to the opening bracket `'('`.
```suggestion
                  ThirdPartyHeap::version());
```

2022-08-12 03:27 UTC, qinsoon commented
I have fixed the indentation. I will update the OpenJDK revision in the binding side once this is merged (as it will have a new commit hash). @wks

2022-08-12 07:06 UTC, wks approved these changes
LGTM

2022-08-15 04:13 UTC, merged